### ISSUE TITLE
Vrnetlab images not supported with virtual EC2 instances

### ISSUE THREAD

**Issue by suhaibasaeed** [friday963/containerlab_on_aws#5]
Thanks a bunch for your work on this amazing project!

A bit of a heads up for everyone else that any images created with vrnetlab for containerlab compatiability i.e. Cisco NXOS/IOS-XE and Junos etc. do not work on the standard EC2 instances as they do not support nested virtualisation.

I got right to the end where I was trying to deploy my topology file then saw the error below:
```
containerlabuser@ip-10-10-1-221:~/containerlab_environment$ sudo containerlab deploy -t sas.clab.yml 
INFO[0000] Containerlab v0.42.0 started                 
INFO[0000] Parsing & checking topology file: sas.clab.yml 
INFO[0000] Could not read docker config: open /root/.docker/config.json: no such file or directory 
INFO[0000] Pulling docker.io/suhaibasaeed/ceos:4.28.7M Docker image 
INFO[0047] Done pulling docker.io/suhaibasaeed/ceos:4.28.7M 
Error: for node "ios1" (vr-csr) the CPU virtualization support is required, but not available
```

There is a (costly) workaround, AWS has bare metal instances you can choose instead e.g. `c5.metal` which does support nested virtualisation that those devices require. These instances cost around $4 an hour. Trying this out I came across a Terraform error which is because the default vCPU count on an AWS account is 32 (metal instances start at 96 vCPUs), so you'll need to raise a ticket to have this limit increased.

```
Error: creating EC2 Instance: VcpuLimitExceeded: You have requested more vCPU capacity than your current vCPU limit of 32 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.
```

So to confirm, I was finally able to get Arista cEOS (not vrnetlab image) and Cisco CSR1000v, Cisco vN9k and Juniper vMX devices working (these 3 were vrnetlab images) with containerlab in AWS.

**Comment by friday963** [comment]
Thank you so much for pointing this out for anyone in the future.  I was not aware of this limitation so I'll be curious if a less exhaustive workaround will be available in the future.  Thanks again!

**Comment by suhaibasaeed** [comment]
Out of interest which images did you get working with your original implementation? Was it just SROS and EOS?

**Comment by friday963** [comment]
@suhaibasaeed That's correct, only those two.  The images you tested are licensed right?  I don't work with Cisco or Juniper much at the moment so I don't have any way of getting or testing them for testing.

**Comment by suhaibasaeed** [comment]
@friday963 We're a Cisco/Juniper shop so yeah I can get a hold of images through the usual channels
